server:
  port: 8082
spring:
  datasource:

    url: jdbc:postgresql://localhost:5432/microservicehotel
    username: postgres
    password: sandy123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  application:
      name: HOTEL-SERVICE
  config:
    import: optional:configserver:http://localhost:8085
#      eureka:
#        instance:
#          prefer-ip-address: true
#
#        client:
#          registerWithEureka: true
#          fetchRegistry: true
#          service-url:
#            defaultZone: http://localhost:8761/eureka
okta:
  oauth2:
    issuer: https://dev-53896844.okta.com/oauth2/default
    audience: api://default